[package]
name = "cw2"
version = { workspace = true }
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Definition and types for the CosmWasm-2 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-minus"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = "0.8.15"
semver = { version = "1.0.20", default-features = false }
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror = "1.0.49"
