[package]
name = "cw2"
version = { workspace = true }
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
description = "Definition and types for the CosmWasm-2 interface"
repository = "https://github.com/CosmWasm/cw-minus"
edition = "2021"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
