version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

workflows:
  version: 2
  test:
    jobs:
      - build_and_test
      - lint
      - coverage

jobs:
  build_and_test:
    docker:
      - image: rust:1.64.0
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - run:
          name: Generate a lockfile
          command: cargo update
      - restore_cache:
          keys:
            - cargocache-v2-utils:1.64.0-{{ checksum "~/project/Cargo.lock" }}
            - cargocache-v2-utils:1.64.0-
      - run:
          name: Build library for native target
          command: cargo build --locked
      - run:
          name: Run unit tests
          command: cargo test --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-v2-utils:1.64.0-{{ checksum "~/project/Cargo.lock" }}

  lint:
    docker:
      - image: rust:1.64.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - run:
          name: Generate a lockfile
          command: cargo update
      - restore_cache:
          keys:
            - cargocache-v2-lint-rust:1.64.0-{{ checksum "Cargo.lock" }}
            - cargocache-v2-lint-rust:1.64.0-
      - run:
          name: Add rustfmt component
          command: rustup component add rustfmt
      - run:
          name: Add clippy component
          command: rustup component add clippy
      - run:
          name: Check formatting of workspace
          command: cargo fmt -- --check
      - run:
          name: Clippy linting on workspace
          command: cargo clippy --all-targets -- -D warnings
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargocache-v2-lint-rust:1.64.0-{{ checksum "Cargo.lock" }}

  coverage:
    # https://circleci.com/developer/images?imageType=machine
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Run tests with coverage
          command: |
            mkdir -p cov
            docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin \
              sh -c "cargo tarpaulin --workspace --skip-clean --frozen --out Xml --output-dir cov"
      - codecov/upload:
          file: cov/cobertura.xml
