[package]
name = "cw-utils"
version = { workspace = true }
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Common helpers for other cw specs"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-minus"

[features]
iterator = ["cosmwasm-std/iterator", "cw-storage-plus/iterator"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = "0.8.15"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror = "1.0.49"

[dev-dependencies]
cw-storage-plus = { workspace = true }
cw-multi-test = { workspace = true }
prost = "0.12.1"
anyhow = "1.0.75"                      # Not used directly but prost-derive does not set a sufficiently high anyhow version

# We don't use these dependencies directly,
# we tighten versions that builds with `-Zminimal-versions` work.
ecdsa = "0.16.8"
