[package]
name = "cw-utils"
version = { workspace = true }
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
description = "Common helpers for other cw specs"
repository = "https://github.com/CosmWasm/cw-minus"
edition = "2021"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

# We don't use these dependencies directly, but we specify versions that work with `-Zminimal-versions`.
ahash = { version = "0.8.7", default-features = false }
num-bigint = { version = "0.4.2", default-features = false }
curve25519-dalek = { version = "4.1.2", default-features = false }

[dev-dependencies]
cw-storage-plus = { workspace = true }
prost = "0.12.1"
anyhow = "1.0.75"              # Not used directly but prost-derive does not set a sufficiently high anyhow version

# We don't use these dependencies directly,
# we tighten versions that builds with `-Zminimal-versions` work.
ecdsa = "0.16.8"
