[package]
name = "cw-utils"
version = "2.0.0-rc.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Common helpers for other cw specs"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-minus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "2.0.0-rc.1"
cosmwasm-std = { version = "2.0.0-rc.1", default-features = false, features = ["std"] }
schemars = "0.8.15"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror = "1.0.49"

[dev-dependencies]
cw-storage-plus = "2.0.0-rc.0"
prost = "0.12.1"
anyhow = "1.0.75"              # Not used directly but prost-derive does not set a sufficiently high anyhow version

# We don't use these dependencies directly,
# we tighten versions that builds with `-Zminimal-versions` work.
ecdsa = "0.16.8"
