name: checks

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.81.0
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets --workspace -- -D warnings
