[package]
name = "cw2"
version = "1.1.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Definition and types for the CosmWasm-2 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cosmwasm-schema = "1.4.0"
cosmwasm-std = { version = "1.4.0", default-features = false }
cw-storage-plus = "1.1.0"
schemars = "0.8.15"
semver = { version = "1.0.20", default-features = false }
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror = "1.0.49"
